# Можно ли создать пользовательское исключение и выбросить его из функции? Приведите пример.

Да, в Java можно создавать пользовательские (настраиваемые) исключения и выбрасывать их из функции. Для этого нужно создать собственный класс исключения, который наследуется от класса `Exception` (или другого подходящего встроенного класса исключений), а затем выбросить его с помощью оператора `throw`.

Пример создания пользовательского исключения и его выбрасывания из функции:

1. Создайте пользовательское исключение:

```java
public class MyCustomException extends Exception {
    public MyCustomException(String message) {
        super(message);
    }
}
```

2. Используйте это исключение в функции:

```java
public class TestCustomException {
    public static void validate(int number) throws MyCustomException {
        if (number < 0) {
            throw new MyCustomException("Number must be non-negative!");
        }
    }

    public static void main(String[] args) {
        try {
            validate(-10);
        } catch (MyCustomException e) {
            System.out.println("Caught custom exception: " + e.getMessage());
        }
    }
}
```

В данном примере:
1. Мы создаем пользовательский класс исключений `MyCustomException`, который наследуется от `Exception`.
2. В методе `validate` проверяем параметр `number`. Если значение отрицательное, выбрасываем `MyCustomException`.
3. В методе `main` вызываем `validate` и обрабатываем исключение в блоке `try-catch`, выводя сообщение исключения на консоль.

Результатом выполнения программы будет:
```
Caught custom exception: Number must be non-negative!
```